networks:
  pantos-service-node:
  pantos-ethereum:
    name: pantos-ethereum-${STACK_IDENTIFIER}-${ETHEREUM_NETWORK-1}
    external: true

services:
  app:
    networks:
      pantos-service-node:
      pantos-ethereum:
    entrypoint: sh -c 'set -a; cat /etc/pantos/ETHEREUM.env && . /etc/pantos/ETHEREUM.env && . /etc/pantos/BNB_CHAIN.env; set +a; exec /app/pantos-service-node.sh'
    environment:
      PANTOS_ENV_FILE: /app/service-node-config.env
      APP_URL: http://localhost:808${INSTANCE-1}
      BNB_CHAIN_PRIVATE_KEY: /app/bnb-data/keystore
      ETHEREUM_PRIVATE_KEY: /app/pantos/eth-data/keystore
    volumes:
      - type: volume
        source: bnb-data
        target: /app/pantos/bnb-data
        read_only: true
      - type: volume
        source: eth-data
        target: /app/pantos/eth-data
        read_only: true
      - type: bind
        source: ./signer_key.pem
        target: /app/service-node-signer.pem
        read_only: true
      - type: bind
        source: ./service-node-config.docker.env
        target: /app/service-node-config.env
        read_only: true
      - type: bind
        source: ${BNB_CHAIN_CONFIG}
        target: /etc/pantos/BNB_CHAIN.env
      - type: bind
        source: ${ETH_CONFIG}
        target: /etc/pantos/ETHEREUM.env
    develop:
      watch:
        - action: sync+restart
          path: service-node-config.docker.env
          target: /app/service-node-config.docker.env

  worker:
    networks:
      pantos-service-node:
      pantos-ethereum:
    entrypoint: sh -c 'set -a; . /etc/pantos/ETHEREUM.env && . /etc/pantos/BNB_CHAIN.env; set +a; exec /app/pantos-service-node-worker.sh'
    environment:
      PANTOS_ENV_FILE: /app/service-node-config.env
      APP_URL: http://localhost:808${INSTANCE-1}
      BNB_CHAIN_PRIVATE_KEY: /app/bnb-data/keystore
      ETHEREUM_PRIVATE_KEY: /app/eth-data/keystore
      PANTOS_STATUS_MONITOR: 1
    ports:
      - 555${INSTANCE-0}:5555
    volumes:
      - type: volume
        source: bnb-data
        target: /app/pantos/bnb-data
        read_only: true
      - type: volume
        source: eth-data
        target: /app/pantos/eth-data
        read_only: true
      - type: bind
        source: ./signer_key.pem
        target: /app/pantos/service-node-signer.pem
        read_only: true
      - type: bind
        source: ./service-node-config.docker.env
        target: /app/pantos/service-node-config.env
        read_only: true
      - type: bind
        source: ${BNB_CHAIN_CONFIG}
        target: /etc/pantos/BNB_CHAIN.env
      - type: bind
        source: ${ETH_CONFIG}
        target: /etc/pantos/ETHEREUM.env
    develop:
      watch:
        - action: sync+restart
          path: service-node-config.docker.env
          target: /app/pantos/service-node-config.docker.env

volumes:
  bnb-data:
    # Requires the same amount of instances as the servicenode
    name: bnb-data-${STACK_IDENTIFIER}-${ETHEREUM_NETWORK-1}
    external: true
  eth-data:
    name: eth-data-${STACK_IDENTIFIER}-${ETHEREUM_NETWORK-1}
    external: true
